# CI = Continuous Integration 끊임 없는 통합


# CD = Continuous Deploy 끊임 없는 배포

# CI/CD, devops, gitops

#env는 git action에서 사용하는 환경변수
env:
  DB_PASSWORD: root

#action 이름
name: pr-test

#action trigger PR오픈시 동작하도록 한다.
on: pull_request


#실행단위 - 메소드같은 애
jobs:
  #job이름
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      # ubuntu에 기본으로 깔려있는 mysql 시작
      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE hwamoktest;' -uroot -proot

      # jdk 17 세팅
      - name: Set up JDK 17
        uses: actions/setup-java@main
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      # gradle test 실행
      - name: Integration Test
        uses: gradle/gradle-build-action@main
        with:
          gradle-version: wrapper
          arguments: test --no-daemon

      # job 실패시 slack으로 알려줌
      - name: send slack message
        uses: 8398a7/action-slack@v3
        if: failure()
        with:
          status: ${{ job.status }}
          fields: repo,message,author,ref,workflow,took
          author_name: ''
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          MATRIX_CONTEXT: ${{ toJson(matrix) }}

